# Generated by Django 6.0.3 on 2026-06-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTrackerApp', '0002_alter_expense_options_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
