# Generated by Django 6.0.3 on 2026-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
